### ISSUE TITLE
API Compatibility Issues

### ISSUE THREAD

**Issue by lilicoding** [caarmen/nounours-android#16]
Dear developers,

We have recently developed a state-of-the-art static analysis tool for uncovering API compatibility issues in Android apps. Applying this tool to open source apps on F-droid, we have exposed a few instances of compatibility issues and submitting them to development teams for a fix. 

For your app, we have found that this project has accessed the following APIs which are available only on an API level higher than the declared minSdkVersion and which are accessed without proper protection. In other words, if those APIs get called at runtime, it will trigger a NoSuchMethodError and thus result in a crash of the running application.

```
<android.service.wallpaper.WallpaperService.Engine: void onDestroy()>:[7,25]
<android.app.Notification.Builder: android.app.Notification.Builder addAction(android.app.Notification.Action)>:[21,25]
<android.service.wallpaper.WallpaperService.Engine: android.view.SurfaceHolder getSurfaceHolder()>:[7,25]
<android.app.ActionBar: void hide()>:[11,25]
<android.service.dreams.DreamService: void setFullscreen(boolean)>:[17,25]
<android.service.wallpaper.WallpaperService.Engine: void onSurfaceChanged(android.view.SurfaceHolder,int,int,int)>:[7,25]
<android.app.Notification.Builder: void <init>(android.content.Context)>:[11,25]
<android.content.res.Resources: int getColor(int,android.content.res.Resources.Theme)>:[23,25]
<android.app.Notification.Builder: android.app.Notification.Builder addAction(int,java.lang.CharSequence,android.app.PendingIntent)>:[16,25]
<android.graphics.drawable.Icon: android.graphics.drawable.Icon createWithResource(android.content.Context,int)>:[23,25]
<android.service.dreams.DreamService: void onDreamingStarted()>:[17,25]
<android.service.dreams.DreamService: void onDreamingStopped()>:[17,25]
<android.service.wallpaper.WallpaperService.Engine: void setTouchEventsEnabled(boolean)>:[7,25]
<android.service.dreams.DreamService: void setInteractive(boolean)>:[17,25]
<android.service.wallpaper.WallpaperService.Engine: void onCreate(android.view.SurfaceHolder)>:[7,25]
<android.app.Activity: void invalidateOptionsMenu()>:[11,25]
<android.app.Notification.Builder: android.app.Notification.Builder setSmallIcon(int)>:[11,25]
<android.app.Notification.Action.Builder: void <init>(android.graphics.drawable.Icon,java.lang.CharSequence,android.app.PendingIntent)>:[23,25]
<android.app.Notification.Builder: android.app.Notification.Builder setContentTitle(java.lang.CharSequence)>:[11,25]
<android.app.Notification.Builder: android.app.Notification.Builder setContentText(java.lang.CharSequence)>:[11,25]
<android.app.Notification.Builder: android.app.Notification getNotification()>:[11,25]
<android.app.Activity: android.app.ActionBar getActionBar()>:[11,25]
<android.service.dreams.DreamService: void setContentView(int)>:[17,25]
<android.app.Notification.Builder: android.app.Notification build()>:[16,25]
<android.service.dreams.DreamService: void onAttachedToWindow()>:[5,25]
<android.app.ActionBar: void show()>:[11,25]
<android.app.Notification.Builder: android.app.Notification.Builder setContentIntent(android.app.PendingIntent)>:[11,25]
<android.service.dreams.DreamService: android.view.View findViewById(int)>:[17,25]
<android.app.ActionBar: void setDisplayHomeAsUpEnabled(boolean)>:[11,25]
<android.content.Context: java.io.File getExternalFilesDir(java.lang.String)>:[8,25]
<android.app.Notification.Action.Builder: android.app.Notification.Action build()>:[21,25]
<android.service.dreams.DreamService: void onDetachedFromWindow()>:[5,25]
<android.view.View: void setSystemUiVisibility(int)>:[11,25]
<android.view.Display: int getRotation()>:[8,25]
```

Note that, because of the nature of the static analysis, we cannot confirm whether the flagged APIs would actually be called at runtime (e.g., unreachable code). However, we still believe that those APIs, which may cause compatibility issues, should not be accessed or at least be accessed with proper protections. 

In addition to the aforementioned APIs (i.e., backward-compatibility), which could cause app crashes if accessed, we have also identified that this project has also accessed some APIs that have been removed from the latest public SDK, making the app possibly suffer from forward-compatibility issues.

NONE

We would be very much appreciated if you can acknowledge to us that those reported APIs are indeed problematic for the project’s long-term stability. please let us know if you need any more information relating to this issue report.

**Comment by caarmen** [comment]
No issues here:


<android.service.wallpaper.WallpaperService.Engine: void onDestroy()>:[7,25]
<android.service.wallpaper.WallpaperService.Engine: android.view.SurfaceHolder getSurfaceHolder()>:[7,25]
<android.service.wallpaper.WallpaperService.Engine: void onSurfaceChanged(android.view.SurfaceHolder,int,int,int)>:[7,25]
<android.service.wallpaper.WallpaperService.Engine: void setTouchEventsEnabled(boolean)>:[7,25]
<android.service.wallpaper.WallpaperService.Engine: void onCreate(android.view.SurfaceHolder)>:[7,25]
The wallpaper feature is only available on api level 7+
In `SettingsActivity.java`:
```java
            // The wallpaper feature isn't available on older devices.
            else if (PREF_LAUNCH_WALLPAPER_SETTINGS.equals(preference.getKey())) {
                if (ApiHelper.getAPILevel() < Build.VERSION_CODES.ECLAIR_MR1
                        || !canLaunchPreferenceIntent(preference)) {
                    preferencesToHide.add(preference);
                }
            }
```

---

<android.app.Notification.Builder: android.app.Notification.Builder addAction(android.app.Notification.Action)>:[21,25]
<android.app.Notification.Builder: android.app.Notification.Builder setSmallIcon(int)>:[11,25]
<android.app.Notification.Action.Builder: void <init>(android.graphics.drawable.Icon,java.lang.CharSequence,android.app.PendingIntent)>:[23,25]
<android.app.Notification.Builder: android.app.Notification.Builder setContentTitle(java.lang.CharSequence)>:[11,25]
<android.app.Notification.Builder: android.app.Notification.Builder setContentText(java.lang.CharSequence)>:[11,25]
<android.app.Notification.Builder: android.app.Notification getNotification()>:[11,25]
<android.app.Notification.Builder: void <init>(android.content.Context)>:[11,25]
<android.app.Notification.Builder: android.app.Notification.Builder addAction(int,java.lang.CharSequence,android.app.PendingIntent)>:[16,25]
<android.app.Notification.Builder: android.app.Notification build()>:[16,25]
<android.app.Notification.Builder: android.app.Notification.Builder setContentIntent(android.app.PendingIntent)>:[11,25]
<android.app.Notification.Action.Builder: android.app.Notification.Action build()>:[21,25]
<android.graphics.drawable.Icon: android.graphics.drawable.Icon createWithResource(android.content.Context,int)>:[23,25]

The `NotificationCompat` class ensures that only the right methods are used to build notifications, for the given android version.

---

<android.service.dreams.DreamService: void setFullscreen(boolean)>:[17,25]
<android.service.dreams.DreamService: void onDreamingStarted()>:[17,25]
<android.service.dreams.DreamService: void onDreamingStopped()>:[17,25]
<android.service.dreams.DreamService: void setInteractive(boolean)>:[17,25]
<android.service.dreams.DreamService: void onDetachedFromWindow()>:[5,25]
<android.service.dreams.DreamService: void setContentView(int)>:[17,25]
<android.service.dreams.DreamService: void onAttachedToWindow()>:[5,25]
<android.service.dreams.DreamService: android.view.View findViewById(int)>:[17,25]

The DreamService feature is only available  on api level 18+
In `SettingsActivity.java`:
```java
            // The dream feature isn't available on older devices.
            else if (PREF_LAUNCH_DREAM_SETTINGS.equals(preference.getKey())) {
                if (ApiHelper.getAPILevel() < Build.VERSION_CODES.JELLY_BEAN_MR2
                        || !canLaunchPreferenceIntent(preference)) {
                    preferencesToHide.add(preference);
                }
```
---

<android.app.ActionBar: void setDisplayHomeAsUpEnabled(boolean)>:[11,25]
This is only called from `ActivityCompat.java` if the api level is 11+

---

<android.app.Activity: android.app.ActionBar getActionBar()>:[11,25]

This is only called on api levels 11+, from these points:
`ActivityCompat.setDisplayHomeAsUpEnabled()`: 11+
`ActivityCompat.setFullScreen()`: 14+

---

<android.app.ActionBar: void hide()>:[11,25]
<android.app.ActionBar: void show()>:[11,25]
<android.view.View: void setSystemUiVisibility(int)>:[11,25]
These are only called on api levels 14+, from `ActivityCompat.setFullScreen()`

---

<android.content.res.Resources: int getColor(int,android.content.res.Resources.Theme)>:[23,25]
This is only called from `ResourcesCompat.getColor()` if the api level is 23+

---

<android.app.Activity: void invalidateOptionsMenu()>:[11,25]
This is only called from `ActivityCompat.invalidateOptionsMenu()`, if the api level is 11+.

---

<android.content.Context: java.io.File getExternalFilesDir(java.lang.String)>:[8,25]
This is only called from `EnvironmentCompat.getExternalFilesDir()`, if the api level is 8+.

---

<android.view.Display: int getRotation()>:[8,25]
This is only called from `DisplayCompat.getRotation()`, if the api level is 8+

**Comment by lilicoding** [comment]
Dear Carmen,

Thank you very much for your feedback, which is very useful for us to improve the quality of our research tool.

Indeed, we actually have only considered the protection of Build.VERSION.SDK_INT (not Build.VERSION.SDK), making us report these false alarms.
BTW, according to the Android developer document, the SDK field has been deprecated in API level 4, meaning that it could be removed or its behaviour could be changed at any time.
So, there might be a need to protect method ApiHelper.getAPILevel() so as to make the app more robust against any unpredictable changes from the framework side.

**Comment by calvarez-ov** [comment]
My app supports minSdk 3, in which `SDK_INT` isn't available. In order to use `SDK_INT` on versions 4+, and `SDK` on version 3, I would first need to know which version I'm on.  But to know which version I'm on, I have to get the sdk level, which means I have to know whether to use `SDK_INT` or `SDK` :P

**Comment by caarmen** [comment]
My app supports minSdk 3, in which `SDK_INT` isn't available. In order to use `SDK_INT` on versions 4+, and `SDK` on version 3, I would first need to know which version I'm on.  But to know which version I'm on, I have to get the sdk level, which means I have to know whether to use `SDK_INT` or `SDK` :P

**Comment by lilicoding** [comment]
Thank you for your reply.
Indeed, SDK_INT is introduced at Level 4. but it could be more robust if you can add a check like this (although it is quite ugly):

```
public static int getAPILevel() {
 int apiLevel = -1;
 try {
  apiLevel = Build.VERSION.SDK_INT;
 }
catch(NoSuchFieldError e) {
 //...
}
if (-1 == apiLevel) {
 apiLevel = Integer.parseInt(Build.VERSION.SDK);
}

return apiLevel;
```

Just my two cents.
